import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import { fetchProducts } from "../../api/products";
export default function UserDashboard() {
    const { data: products = [], isLoading, isError } = useQuery({
        queryKey: ["user", "products"],
        queryFn: () => fetchProducts()
    });
    return (_jsx("div", { className: "min-h-screen bg-ash p-10", children: _jsxs("div", { className: "mx-auto max-w-6xl rounded-xl bg-white p-8 shadow-md", children: [_jsx("h1", { className: "text-2xl font-semibold text-slate-800", children: "Browse Products" }), _jsx("p", { className: "mt-2 text-sm text-slate-500", children: "Select items from any warehouse to place your order (coming soon)." }), isLoading && _jsx("p", { className: "mt-6 text-sm text-slate-500", children: "Loading available products..." }), isError && _jsx("p", { className: "mt-6 text-sm text-red-500", children: "Unable to load products right now." }), !isLoading && products.length === 0 && (_jsx("p", { className: "mt-6 text-sm text-slate-500", children: "No products are currently available." })), !isLoading && products.length > 0 && (_jsx("div", { className: "mt-6 overflow-x-auto", children: _jsxs("table", { className: "w-full table-auto text-left text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b bg-slate-50 text-xs uppercase tracking-widest text-slate-500", children: [_jsx("th", { className: "px-4 py-2", children: "Product" }), _jsx("th", { className: "px-4 py-2", children: "SKU" }), _jsx("th", { className: "px-4 py-2", children: "Category" }), _jsx("th", { className: "px-4 py-2", children: "Vendor" }), _jsx("th", { className: "px-4 py-2", children: "In Stock" }), _jsx("th", { className: "px-4 py-2", children: "Warehouse" })] }) }), _jsx("tbody", { children: products.map((product) => (_jsxs("tr", { className: "border-b last:border-none", children: [_jsx("td", { className: "px-4 py-3 font-medium text-slate-800", children: product.name }), _jsx("td", { className: "px-4 py-3 text-slate-600", children: product.sku }), _jsx("td", { className: "px-4 py-3 text-slate-600", children: product.category }), _jsx("td", { className: "px-4 py-3 text-slate-600", children: product.vendor }), _jsx("td", { className: "px-4 py-3 text-slate-600", children: product.currentStock }), _jsxs("td", { className: "px-4 py-3 text-slate-600", children: [product.warehouseName, _jsx("span", { className: "ml-2 text-xs text-slate-400", children: product.warehouseCode })] })] }, product.id))) })] }) }))] }) }));
}
